### ISSUE TITLE
Not validating answer

### ISSUE THREAD

**Issue by onlyyouandty** [kiskolabs/humanizer#43]
When I leave the answer field blank, or enter the wrong answer. It still passes the form.

Here is the params from the create method:
Parameters: {"utf8"=>"✓", "authenticity_token"=>"FsNEHP1PUmeUpgDB7gXFH1KWrV63uDhb8rvZMze/arY=", "message"=>{"name"=>"", "email"=>"*******@gmail.com", "subject"=>"", "content"=>"Hamama", "humanizer_answer"=>"4", "humanizer_question_id"=>""}, "commit"=>"Send us message"}

I noticed the "humanizer_question_id" is empty.

**Comment by vesan** [comment]
Hi @TaiwoAyanleye!

Are you calling `require_human_on` in the model? Can you share the other humanizer related code you've used in your app?

**Comment by TaiwoAyanleye** [comment]
Hi Vesan,

Here is how the model looks:
```
class Message
	include ActiveModel::Model
	
	#Humanizer
	include Humanizer
  	require_human_on :new
  	require_human_on :create
  	
	attr_accessor :name, :email, :subject, :content, :humanizer_answer, :humanizer_question_id

	validates :email, :content, presence: true
end

``` 

And here is my views new.html.erb

```
<%= f.label :humanizer_answer, @message.humanizer_question %>
<%= f.text_field :humanizer_answer %>
<%= f.hidden_field :humanizer_question_id %>

**Comment by Grantlyk** [comment]
I'm having the exact same issue

**Comment by craigsheen** [comment]
Should the code in the model not be

```ruby
require_human_on :create
```

**Comment by Grantlyk** [comment]
I have that as my code and it still doesn't work

**Comment by krim** [comment]
use "require_human_on"  without params

**Comment by vesan** [comment]
@craigsheen & @krim are both right. You need to use either :create or no params. @onlyyouandty this should fix your problem.

@Grantlyk You can override the method `humanizer_correct_answer?` to return false and see if that blocks the model from being saved (it should). Like this:

```ruby
def humanizer_correct_answer?
  false
end
```

**Comment by onlyyouandty** [comment]
Right

**Comment by mayanktap** [comment]
Answer is not validated ... 
-----------------------------------------
Model File : 
MailToFriend.class_eval do
	include Humanizer
  require_human_on :send_mail	
end

----------------------------------------

Controller File : 
EmailSenderController.class_eval do
  include I18nHelper
  before_filter :set_locale

  include MobileidentifierHelper
  helper_method :mobile_device?
  before_filter :check_for_mobile, :only => [:send_mail]

  def login
    redirect_to "/user/sign_in"
    flash[:notice] = "You need to sign in or sign up before continuing."
  end

  def send_mail
    
    if @object.nil?
        render_404
    else
      if params[:mail_to_friend] 
        params[:mail_to_friend][:sender_email]=params[:mail_to_friend][:sender_email].strip unless params[:mail_to_friend][:sender_email].nil?
        params[:mail_to_friend][:recipient_email]=params[:mail_to_friend][:recipient_email].strip unless params[:mail_to_friend][:recipient_email].nil?
      end
      if request.get?
        @mail_to_friend = MailToFriend.new(:sender_email => current_user.try(:email))
      else
        
          mail_to_friend
      end
    end  
  end

end

-----------------------------------------------------------
Actually on applying debugger in humanizer.rb file I came to know that humanizer_check_answer method was not hit.

**Comment by onlyyouandty** [comment]
@mayanktap, you will need to do either `require_human_on` or `require_human_on :create` using it with other params like `require_human_on :send_mail` will not work according to @vesan

**Comment by vesan** [comment]
@mayanktap, as you can see [in the code](https://github.com/kiskolabs/humanizer/blob/38b20241278d5827faec277de9eec9dc3ed2b08d/lib/humanizer.rb#L66) the first parameter is passed as `:on` option. So it will become `validate :humanizer_check_answer, on: :send_mail` which prevents the whole validation from being run.

**Comment by mayanktap** [comment]
I tried using **require_human_on**  which starts my validation process but _:humanizer_answer_ gets the "nil" value which prevents user to send mail instead of writing correct answer for the question asked.

And same goes with the case **require_human_on**.

**Comment by mayanktap** [comment]
I am waiting for your valuable feedback.
On using **_require_human_on_** directly starts my answer validation process but for all cases (both for wrong and correct answer) it prints the common statement that "Humanizer answer You're not a human". On using debugger I came to now that _humanizer_answer_ stores _nil_.

**Comment by vesan** [comment]
@mayanktap Can you post bigger code example? Hard to say what is wrong when the code example doesn't show how the `humanizer_answer` is set.

**Comment by mayanktap** [comment]
[controller_file.txt](https://github.com/kiskolabs/humanizer/files/323498/controller_file.txt)
[humanizer_ruby.txt](https://github.com/kiskolabs/humanizer/files/323495/humanizer_ruby.txt)
[model_file.txt](https://github.com/kiskolabs/humanizer/files/323496/model_file.txt)
[view_file.txt](https://github.com/kiskolabs/humanizer/files/323497/view_file.txt)

These are the controller, model and view file of the page along with your humanizer.rb file. Basically I am getting nil value for _humanizer_answer_(attr_accessor). _humanizer_answer_ is used in view file as stated by you.

**Comment by vesan** [comment]
@mayanktap `params[:mail_to_friend][:humanizer_answer]` should have the answer provided by the user and `params[:mail_to_friend][:humanizer_question_id]` should have the question id. Those should be set on `@mail_to_friend` by for example `@mail_to_friend.attributes = params[:mail_to_friend]`.
