### ISSUE TITLE
Always the same question

### ISSUE THREAD

**Issue by wernerlaude** [kiskolabs/humanizer#48]
It is a nice gem.
Is it possible to organize to get a different question every time I call the contact  form.
It's changing on reload (if the sending fails) but I dont like to get the same question (the first in row: Two plus two?) every time I go to the form.

Thanks

**Comment by vesan** [comment]
Hi @wernerlaude,

It does randomize the first picked question: https://github.com/kiskolabs/humanizer/blob/0a683f8a3a21e12454c64fa70b07636be422622b/lib/humanizer.rb#L52

Are you doing something special or using it like described in the README?

**Comment by wernerlaude** [comment]
Nothing special...all like in README. No problem if validation fails, then it takes a random new question..but normal call always picks q1..

**Comment by vesan** [comment]
Awesome!
