### ISSUE TITLE
Disabling the mechanism from the controller?

### ISSUE THREAD

**Issue by jmuheim** [kiskolabs/humanizer#50]
I have a `User` model:

```rb
class User < ApplicationRecord
  require_human_on :create
end
```

When a guest wants to register, I display the CAPTCHA. But when an already logged in admin wants to create user manually, I don't show it.

At the time being, the easiest way to disable the CAPTCHA in the latter case is to set the question id and answer manually in the controller:

```rb
  def create
    # Make captcha mechanism pass automatically (only needed for new registrations, not when creating a user manually)
    @user.humanizer_question_id = '16'
    @user.humanizer_answer      = '5'

    @user.save
    respond_with @user
  end
```

But this is pretty ugly. Is there a better way to do this?

**Comment by matiaskorhonen** [comment]
There are instructions for bypassing the validation in the readme: https://github.com/kiskolabs/humanizer#skipping-validation

**Comment by jmuheim** [comment]
It feels a bit clumsy to add custom attributes to the model itself. Wouldn't it be nicer to have this feature hidden within the default features of humanizer?

I'd like something in the controller like this:

```rb
without_humanizer do
    @user.save
end
```

**Comment by vesan** [comment]
@jmuheim If we would hide it, it would not be as flexible.

Now you can use whatever condition you need for the `require_human_on` call.
