### ISSUE TITLE
Suggesting slightly better default questions

### ISSUE THREAD

**Issue by gerard76** [kiskolabs/humanizer#52]
Thanks for the gem. We have been using for years. We use the default questions and some of our own.
Lately I noticed a lot of bypasses. About 20% of a thousand requests got past the humanizer in the last 2 days.

Turns out the questions with minus, times en plus and numerical answer were solvable. 'Two plus two?', 'Five times two is what?', 'What is 14 minus 4?' and the likes.

Examples of numerical questions that are not (yet) solved are:
- What is fifteen divided by three?
- What number comes after 20?
- Ten divided by two is what?
- What is the number before twelve?

I know it will never be perfect, but for now a slightly improved default en.yml would be nice to get a better experience

**Comment by vesan** [comment]
Thanks for the feedback! Would you be willing to open a pull request with your suggested updates?
